// Sample data for development and demo purposes
export const sampleProducts = [
  {
    id: 1,
    name: "Arctic Menthol Blast",
    flavor_profile: "Μέντα",
    product_url: "https://vaporstation.gr/product/arctic-menthol-blast",
    final_volume: "60ml",
    description: "Ένα δροσερό μείγμα μέντας και ευκαλύπτου που σε ταξιδεύει στην Αρκτική. Τέλειο για τους λάτρεις της δροσιάς.",
    image_url: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400&h=400&fit=crop",
    ingredients: ["Μέντα", "Ευκάλυπτος", "Πάγος"],
    price: 8.50,
    ice_intensity: 5,
    sweetness_intensity: 1,
    country: "Ηνωμένο Βασίλειο",
    brand: "IceLab",
  },
  {
    id: 2,
    name: "Tropical Paradise",
    flavor_profile: "Φρούτα",
    product_url: "https://vaporstation.gr/product/tropical-paradise",
    final_volume: "60ml",
    description: "Εξωτικό μείγμα μάνγκο, ανανά και πάσιον φρουτ. Καλοκαίρι σε κάθε εισπνοή.",
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=400&fit=crop",
    ingredients: ["Μάνγκο", "Ανανάς", "Πάσιον Φρουτ"],
    price: 9.00,
    ice_intensity: 2,
    sweetness_intensity: 4,
    country: "Μαλαισία",
    brand: "Fruity Clouds",
  },
  {
    id: 3,
    name: "Classic Tobacco Gold",
    flavor_profile: "Καπνικά",
    product_url: "https://vaporstation.gr/product/classic-tobacco-gold",
    final_volume: "30ml",
    description: "Παραδοσιακή γεύση καπνού με νότες καραμέλας και βανίλιας. Κλασική επιλογή.",
    image_url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop",
    ingredients: ["Καπνός", "Καραμέλα", "Βανίλια"],
    price: 7.50,
    ice_intensity: 0,
    sweetness_intensity: 3,
    country: "Ιταλία",
    brand: "Vaporart",
  },
  {
    id: 4,
    name: "Berry Explosion",
    flavor_profile: "Φρούτα",
    product_url: "https://vaporstation.gr/product/berry-explosion",
    final_volume: "60ml",
    description: "Ένα πλούσιο μείγμα φράουλας, βατόμουρου και blueberry. Φρουτένια απόλαυση σε κάθε puff.",
    image_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop",
    ingredients: ["Φράουλα", "Βατόμουρο", "Blueberry"],
    price: 8.50,
    ice_intensity: 1,
    sweetness_intensity: 5,
    country: "Ηνωμένο Βασίλειο",
    brand: "Vampire Vape",
  },
  {
    id: 5,
    name: "Vanilla Custard Dream",
    flavor_profile: "Κρέμες",
    product_url: "https://vaporstation.gr/product/vanilla-custard-dream",
    final_volume: "30ml",
    description: "Βελούδινη κρέμα βανίλιας με νότες μπισκότου. Η τέλεια γλυκιά απόδραση.",
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=400&fit=crop",
    ingredients: ["Βανίλια", "Κρέμα", "Μπισκότο"],
    price: 9.50,
    ice_intensity: 0,
    sweetness_intensity: 5,
    country: "ΗΠΑ",
    brand: "Loaded",
  },
  {
    id: 6,
    name: "Lemon Ice Tea",
    flavor_profile: "Ροφήματα",
    product_url: "https://vaporstation.gr/product/lemon-ice-tea",
    final_volume: "60ml",
    description: "Δροσιστικό παγωμένο τσάι λεμονιού. Ιδανικό για τις ζεστές μέρες.",
    image_url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop",
    ingredients: ["Λεμόνι", "Τσάι", "Πάγος"],
    price: 8.00,
    ice_intensity: 3,
    sweetness_intensity: 2,
    country: "Ελλάδα",
    brand: "Atmos Lab",
  },
  {
    id: 7,
    name: "Watermelon Chill",
    flavor_profile: "Φρούτα",
    product_url: "https://vaporstation.gr/product/watermelon-chill",
    final_volume: "120ml",
    description: "Ζουμερό καρπούζι με μια πινελιά δροσιάς. Καλοκαιρινή απόλαυση.",
    image_url: "https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=400&fit=crop",
    ingredients: ["Καρπούζι", "Μέντα", "Πάγος"],
    price: 12.00,
    ice_intensity: 4,
    sweetness_intensity: 3,
    country: "Μαλαισία",
    brand: "Fruity Clouds",
  },
  {
    id: 8,
    name: "Coffee Latte",
    flavor_profile: "Ροφήματα",
    product_url: "https://vaporstation.gr/product/coffee-latte",
    final_volume: "30ml",
    description: "Πλούσιος espresso με κρεμώδες γάλα. Η τέλεια πρωινή συντροφιά.",
    image_url: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop",
    ingredients: ["Καφές", "Γάλα", "Κρέμα"],
    price: 7.50,
    ice_intensity: 0,
    sweetness_intensity: 2,
    country: "Ιταλία",
    brand: "Vaporart",
  },
  {
    id: 9,
    name: "Grape Frost",
    flavor_profile: "Φρούτα",
    product_url: "https://vaporstation.gr/product/grape-frost",
    final_volume: "60ml",
    description: "Γλυκό σταφύλι με παγωμένη δροσιά. Μια γεύση που σε κερδίζει.",
    image_url: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=400&fit=crop",
    ingredients: ["Σταφύλι", "Μέντα", "Πάγος"],
    price: 8.50,
    ice_intensity: 3,
    sweetness_intensity: 4,
    country: "Ηνωμένο Βασίλειο",
    brand: "IceLab",
  },
  {
    id: 10,
    name: "Pistachio Cream",
    flavor_profile: "Κρέμες",
    product_url: "https://vaporstation.gr/product/pistachio-cream",
    final_volume: "30ml",
    description: "Κρεμώδες φυστίκι Αιγίνης με βανίλια. Ελληνική γαστρονομία σε υγρό.",
    image_url: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400&h=400&fit=crop",
    ingredients: ["Φυστίκι", "Κρέμα", "Βανίλια"],
    price: 10.00,
    ice_intensity: 0,
    sweetness_intensity: 4,
    country: "Ελλάδα",
    brand: "Atmos Lab",
  },
  {
    id: 11,
    name: "Spearmint Fresh",
    flavor_profile: "Μέντα",
    product_url: "https://vaporstation.gr/product/spearmint-fresh",
    final_volume: "60ml",
    description: "Καθαρή δυόσμος με ήπια γλυκύτητα. Απλή, δροσερή, αποτελεσματική.",
    image_url: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=400&fit=crop",
    ingredients: ["Δυόσμος", "Μέντα"],
    price: 7.00,
    ice_intensity: 4,
    sweetness_intensity: 1,
    country: "ΗΠΑ",
    brand: "Halo",
  },
  {
    id: 12,
    name: "Caramel Tobacco",
    flavor_profile: "Καπνικά",
    product_url: "https://vaporstation.gr/product/caramel-tobacco",
    final_volume: "60ml",
    description: "Ήπιος καπνός Virginia με γλυκιά καραμέλα. Η τέλεια ισορροπία.",
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop",
    ingredients: ["Καπνός Virginia", "Καραμέλα", "Βανίλια"],
    price: 8.50,
    ice_intensity: 0,
    sweetness_intensity: 3,
    country: "Ελλάδα",
    brand: "VaporStation",
  },
]
